INSERT INTO inventarys (nombre, precio,unidad,provedor,creation_date) VALUES ('ARROZ', 3500,'KG','yulit', NOW());
INSERT INTO inventarys (nombre, precio,unidad,provedor,creation_date) VALUES ('LECHE', 9000,'L','paola', NOW());
INSERT INTO inventarys (nombre, precio,unidad,provedor,creation_date) VALUES ('PASTA', 10000,'G','lolcolombia', NOW());
INSERT INTO inventarys (nombre, precio,unidad,provedor,creation_date) VALUES ('HUEVOS', 2000,'G','lolcolombia', NOW());
INSERT INTO inventarys (nombre, precio,unidad,provedor,creation_date) VALUES ('JUGUITO DE NARANJA', 333,'L','lolcolombia', NOW());
INSERT INTO inventarys (nombre, precio,unidad,provedor,creation_date) VALUES ('SAL', 6080,'KG','lolcolombia', NOW());
INSERT INTO inventarys (nombre, precio,unidad,provedor,creation_date) VALUES ('AZUCAR', 5000,'KG','lolcolombia', NOW());
INSERT INTO inventarys (nombre, precio,unidad,provedor,creation_date) VALUES ('MERMELADA', 1231,'KG','lolcolombia', NOW());
INSERT INTO inventarys (nombre, precio,unidad,provedor,creation_date) VALUES ('CARNE', 55660,'KG','lolcolombia', NOW());
INSERT INTO inventarys (nombre, precio,unidad,provedor,creation_date) VALUES ('POLLO', 67000,'KG','lolcolombia', NOW());